using TaskStatus = MiniWebApp.TaskAPI.Domain.Entities.Enums.TaskStatus;

namespace MiniWebApp.TaskAPI.Domain.Entities;

/// <summary>
/// Represents a task in the Task Manager system.
/// </summary>
/// <remarks>
/// TaskItem is a mutable entity that supports:<br/>
/// - Full CRUD operations<br/>
/// - Status and priority tracking<br/>
/// - Optimistic concurrency using a ticks-based LastModified value<br/>
/// <br/>
/// <b>Concurrency:</b><br/>
/// - The <see cref="LastModified"/> field is used as a concurrency token.<br/>
/// - On update, EF Core ensures the value matches the original ticks value.<br/>
/// - If not, a <c>DbUpdateConcurrencyException</c> is thrown.<br/>
/// <br/>
/// <b>Database mapping:</b><br/>
/// - Table: <c>tasks</c><br/>
/// - Snake_case column naming<br/>
/// - <see cref="LastModified"/> stored as ticks (long)<br/>
/// <br/>
/// <b>Typical use cases:</b><br/>
/// - Personal task management<br/>
/// - Workflow tracking<br/>
/// - Incremental sync using LastModified<br/>
/// </remarks>
public class TaskItem
{
    /// <summary>
    /// Unique identifier of the task.
    /// </summary>
    /// <remarks>
    /// - Generated by the application (GUID)
    /// - Not database-generated
    /// </remarks>
    public Guid Id { get; set; }

    /// <summary>
    /// Short title describing the task.
    /// </summary>
    /// <remarks>
    /// Required. Maximum length: 200 characters.
    /// </remarks>
    public string Title { get; set; } = null!;

    /// <summary>
    /// Optional detailed description of the task.
    /// </summary>
    /// <remarks>
    /// Maximum length: 1000 characters.
    /// </remarks>
    public string? Description { get; set; }

    /// <summary>
    /// Current workflow status of the task.
    /// </summary>
    /// <remarks>
    /// Possible values: Pending, InProgress, Completed.
    /// </remarks>
    public TaskStatus Status { get; set; }

    /// <summary>
    /// Priority level of the task.
    /// </summary>
    /// <remarks>
    /// Used for ordering and filtering tasks.
    /// </remarks>
    public TaskPriority Priority { get; set; }

    /// <summary>
    /// Optional due date for completing the task.
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// Timestamp of the last modification to the task.
    /// </summary>
    /// <remarks>
    /// - Used as an optimistic concurrency token
    /// - Stored as ticks in the database
    /// - Updated on every write operation
    /// </remarks>
    public DateTime LastModified { get; set; }
}

